// Generated by marketplace.loader — do not edit by hand.
// Inlined (not fetched) so the storefront works from file://, GitHub Pages, and any subpath.
window.CATALOG_DATA = [
 {
  "id": "abandoned-object",
  "name": "Abandoned Object Detection",
  "tagline": "The bag that nobody picked back up, flagged in under a minute.",
  "category": "People & Safety",
  "tier": "enterprise",
  "requires_gpu": true,
  "config_keys": [
   "abandon_seconds",
   "object_classes",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 public area",
   "abandon_seconds": "int (default 45)",
   "object_classes": "list of COCO ids (default bags/luggage)"
  }
 },
 {
  "id": "after-hours-activity",
  "name": "After-Hours Activity",
  "tagline": "Person in the building at 2am. Clip attached. Your phone, not your answering service.",
  "category": "Security & Access",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "closed_hours"
  ],
  "config_schema": {
   "closed_hours": "[start,end] (default [20,6])"
  }
 },
 {
  "id": "aggression-posture",
  "name": "Aggression Early-Warning",
  "tagline": "Arms up, movements erratic \u2014 staff get seconds of warning.",
  "category": "People & Safety",
  "tier": "enterprise",
  "requires_gpu": true,
  "config_keys": [
   "confidence",
   "sustain_seconds"
  ],
  "config_schema": {
   "confidence": "float (default 0.5)",
   "sustain_seconds": "float (default 2.5)"
  }
 },
 {
  "id": "atm-vestibule-watch",
  "name": "ATM Vestibule Watch",
  "tagline": "Two people, one transaction, 1am. The branch sees it live.",
  "category": "Security & Access",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "closed_hours",
   "dwell_minutes",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 ATM area",
   "closed_hours": "[start,end] (default [22,6])",
   "dwell_minutes": "int (default 5)"
  }
 },
 {
  "id": "banquet-setup-verify",
  "name": "Banquet Setup Verification",
  "tagline": "6pm wedding, 4:30pm room not set. The alert went out at 4:31.",
  "category": "Intelligence",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "min_density_ratio",
   "verify_hour",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 event room",
   "verify_hour": "int \u2014 hour to check setup (default 15)",
   "min_density_ratio": "float \u2014 vs set-up baseline (default 0.7)"
  }
 },
 {
  "id": "bus-loop-safety",
  "name": "Bus Loop Safety",
  "tagline": "A car in the bus loop at 8:15am is a headline you don't want.",
  "category": "People & Safety",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "bell_windows",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 bus loop",
   "bell_windows": "[[start,end],...] hours (default [[7,9],[14,16]])"
  }
 },
 {
  "id": "camera-tamper",
  "name": "Camera Tamper Detection",
  "tagline": "Sprayed, covered, or turned \u2014 you find out in seconds, not after the theft.",
  "category": "Property & Liability",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "diff_ratio",
   "edge_drop_ratio"
  ],
  "config_schema": {
   "edge_drop_ratio": "float vs baseline (default 0.6)",
   "diff_ratio": "float persistent-diff (default 0.5)"
  }
 },
 {
  "id": "cart-path-violation",
  "name": "Cart Path Violation",
  "tagline": "Cart-path-only day. Cart on the fairway at 14. Photo attached.",
  "category": "Compliance",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "active",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 protected turf area",
   "active": "bool \u2014 enable on path-only days"
  }
 },
 {
  "id": "change-machine-watch",
  "name": "Change Machine Watch",
  "tagline": "Twenty minutes at the change machine at 4am. That's not laundry.",
  "category": "Security & Access",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "dwell_minutes",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 change machine approach",
   "dwell_minutes": "int (default 12)"
  }
 },
 {
  "id": "child-safety-zone",
  "name": "Child Safety Zone",
  "tagline": "A small person near the pool gate at 9pm. Phone alert, right now.",
  "category": "People & Safety",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "max_height_ratio",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 restricted area",
   "max_height_ratio": "float \u2014 child height proxy vs frame (default 0.35)"
  }
 },
 {
  "id": "clubhouse-flow",
  "name": "Clubhouse Amenity Flow",
  "tagline": "The patio does 3x the grill on Fridays. Staffing finally matches.",
  "category": "Intelligence",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "digest_hour",
   "zones"
  ],
  "config_schema": {
   "zones": "map of amenity-name \u2192 polygon",
   "digest_hour": "int (default 22)"
  }
 },
 {
  "id": "conveyor-jam",
  "name": "Conveyor Jam Detector",
  "tagline": "A box that stops moving on the belt is a jam. Now you know in seconds.",
  "category": "Manufacturing & Warehouse",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "jam_seconds",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 belt area",
   "jam_seconds": "int \u2014 stationary threshold (default 20)"
  }
 },
 {
  "id": "coolant-leak-visual",
  "name": "Leak Pooling Watch",
  "tagline": "The puddle under the CRAC unit, caught when it was a mop job.",
  "category": "Property & Liability",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "growth_ratio",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 floor area near equipment",
   "growth_ratio": "float \u2014 dark-region growth (default 0.03)"
  }
 },
 {
  "id": "crane-exclusion",
  "name": "Crane Exclusion Zone",
  "tagline": "Person under the load path. The lift director's phone buzzes.",
  "category": "People & Safety",
  "tier": "enterprise",
  "requires_gpu": true,
  "config_keys": [
   "hold_ms",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 exclusion area under/near crane",
   "hold_ms": "int (default 500)"
  }
 },
 {
  "id": "crematory-access",
  "name": "Crematory Access Log",
  "tagline": "Every entry to the crematory, timestamped, with a clip. The log writes itself.",
  "category": "Compliance",
  "tier": "enterprise",
  "requires_gpu": true,
  "config_keys": [
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 crematory door approach"
  }
 },
 {
  "id": "crowd-density",
  "name": "Crowd Density Alert",
  "tagline": "The floor crossed its density cap at 11:43pm. You knew at 11:43pm.",
  "category": "People & Safety",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "hold_seconds",
   "max_persons",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 venue floor",
   "max_persons": "int (default 50)",
   "hold_seconds": "int (default 20)"
  }
 },
 {
  "id": "curbside-arrival",
  "name": "Curbside Pickup Arrival",
  "tagline": "Customer in the pickup lane \u2014 staff know before the app notification.",
  "category": "Automotive & Parking",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 curbside lane"
  }
 },
 {
  "id": "customer-wait-alert",
  "name": "Unacknowledged Customer Alert",
  "tagline": "Nobody greeted them for 3 minutes. Now you know.",
  "category": "Retail & QSR",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "staff_zone",
   "wait_seconds",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 customer service area",
   "staff_zone": "polygon \u2014 where staff are expected",
   "wait_seconds": "int \u2014 threshold (default 180)"
  }
 },
 {
  "id": "daycare-ratio",
  "name": "Classroom Ratio Watch",
  "tagline": "9 toddlers, 1 adult, room 3. Ratio alert before the licensor arrives.",
  "category": "Compliance",
  "tier": "enterprise",
  "requires_gpu": true,
  "config_keys": [
   "child_height_ratio",
   "hold_seconds",
   "max_ratio",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 classroom",
   "max_ratio": "float \u2014 children per adult (default 8)",
   "child_height_ratio": "float \u2014 child proxy (default 0.38)",
   "hold_seconds": "int (default 120)"
  }
 },
 {
  "id": "desk-hotel-mapping",
  "name": "Desk Utilization Map",
  "tagline": "Row 4 sits empty every day. Row 1 is full by 9. Now you can prove it.",
  "category": "Intelligence",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "desks",
   "digest_hour"
  ],
  "config_schema": {
   "desks": "map of desk-name \u2192 polygon",
   "digest_hour": "int (default 17)"
  }
 },
 {
  "id": "detail-qc-walk",
  "name": "Detail QC Flag",
  "tagline": "Foam still on the rear quarter at delivery. Flagged before the customer saw it.",
  "category": "Automotive & Parking",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "residue_ratio",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 QC/delivery area",
   "residue_ratio": "float \u2014 bright-patch threshold (default 0.06)"
  }
 },
 {
  "id": "dispensary-capacity",
  "name": "Sales Floor Capacity",
  "tagline": "Licensed cap is 30. You're at 34. The door got the alert, not the inspector.",
  "category": "Compliance",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "hold_seconds",
   "max_persons",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 sales floor",
   "max_persons": "int \u2014 licensed cap",
   "hold_seconds": "int (default 30)"
  }
 },
 {
  "id": "dock-slip-occupancy",
  "name": "Slip Occupancy Log",
  "tagline": "Slip 22 has a boat that isn't on the register. The harbormaster has the frame.",
  "category": "Intelligence",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "check_hour",
   "min_object_ratio",
   "slips"
  ],
  "config_schema": {
   "slips": "map of slip-name \u2192 polygon",
   "check_hour": "int (default 6)",
   "min_object_ratio": "float \u2014 boat-sized object (default 0.02)"
  }
 },
 {
  "id": "dock-utilization",
  "name": "Dock Door Utilization",
  "tagline": "Every dock door's busy time, measured \u2014 not argued about.",
  "category": "Manufacturing & Warehouse",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "docks"
  ],
  "config_schema": {
   "docks": "map of dock-name \u2192 polygon"
  }
 },
 {
  "id": "door-propped",
  "name": "Door Propped Open",
  "tagline": "The back door propped for a smoke break is your inventory walking out.",
  "category": "Property & Liability",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "propped_seconds",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 door area",
   "propped_seconds": "int (default 90)"
  }
 },
 {
  "id": "drive-off-alert",
  "name": "Drive-Off Alert",
  "tagline": "Tank filled, nobody walked in, car gone. Alert before the plate leaves frame.",
  "category": "Automotive & Parking",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "store_line",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 pump island",
   "store_line": "2-point line across store entry"
  }
 },
 {
  "id": "drive-thru-timer",
  "name": "Drive-Thru Service Timer",
  "tagline": "Every car's time, order point to window exit \u2014 automatically.",
  "category": "Retail & QSR",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "exit_zone",
   "order_zone",
   "slow_seconds"
  ],
  "config_schema": {
   "order_zone": "polygon \u2014 speaker/order point",
   "exit_zone": "polygon \u2014 past the window",
   "slow_seconds": "int \u2014 per-car alert threshold (default 240)"
  }
 },
 {
  "id": "driver-cab-time",
  "name": "Driver-in-Cab Dock Interlock",
  "tagline": "Driver in the cab while the forklift's in the trailer. Alert the dock.",
  "category": "Manufacturing & Warehouse",
  "tier": "enterprise",
  "requires_gpu": true,
  "config_keys": [
   "cab_zone",
   "dock_zone"
  ],
  "config_schema": {
   "cab_zone": "polygon \u2014 truck cab area",
   "dock_zone": "polygon \u2014 active dock"
  }
 },
 {
  "id": "dwell-analytics",
  "name": "Zone Dwell Analytics",
  "tagline": "Which displays get looked at. Which aisles get skipped.",
  "category": "Retail & QSR",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "digest_hour",
   "zones"
  ],
  "config_schema": {
   "zones": "map of zone-name \u2192 polygon",
   "digest_hour": "int \u2014 hour (0-23) to emit daily summary (default 21)"
  }
 },
 {
  "id": "ev-charger-blocked",
  "name": "EV Charger Blocked",
  "tagline": "The stall is for charging, not all-day parking.",
  "category": "Automotive & Parking",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "max_minutes",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 EV stall",
   "max_minutes": "int \u2014 allowed dwell (default 120)"
  }
 },
 {
  "id": "fire-exit-blocked",
  "name": "Fire Exit Blocked",
  "tagline": "A pallet in front of the fire exit is a five-figure fine. Not anymore.",
  "category": "Property & Liability",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "blocked_seconds",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 egress area",
   "blocked_seconds": "int (default 60)"
  }
 },
 {
  "id": "footfall-counter",
  "name": "Footfall & Occupancy Counter",
  "tagline": "Real door counts and live occupancy, from the camera you already own.",
  "category": "Retail & QSR",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "count_line",
   "occupancy_alert"
  ],
  "config_schema": {
   "count_line": "2-point line across the entrance",
   "occupancy_alert": "int \u2014 optional max occupancy alert"
  }
 },
 {
  "id": "forecourt-loiter",
  "name": "Forecourt Loitering Watch",
  "tagline": "Someone's been standing between the pumps for 15 minutes at 1am.",
  "category": "Security & Access",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "after_hours",
   "loiter_minutes",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 forecourt",
   "after_hours": "[start,end] (default [23,5])",
   "loiter_minutes": "int (default 10)"
  }
 },
 {
  "id": "forklift-speed",
  "name": "Forklift Speed Governor",
  "tagline": "Speeding forklifts in pedestrian aisles, caught on camera you already own.",
  "category": "Manufacturing & Warehouse",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "max_px_per_sec",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 pedestrian-shared lane",
   "max_px_per_sec": "float \u2014 calibrated speed proxy (default 0.15 normalized/s)"
  }
 },
 {
  "id": "fuel-dock-dwell",
  "name": "Fuel Dock Dwell",
  "tagline": "That boat's been on the fuel dock 45 minutes. The line is three deep.",
  "category": "Intelligence",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "max_minutes",
   "min_object_ratio",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 fuel dock",
   "max_minutes": "int (default 25)",
   "min_object_ratio": "float (default 0.02)"
  }
 },
 {
  "id": "funeral-home-flow",
  "name": "Visitation Room Flow",
  "tagline": "The Johnson visitation ran 3 hours with 140 visitors. Documented for the family.",
  "category": "Intelligence",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "visitation_windows",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 visitation room",
   "visitation_windows": "[[start,end],...] hours"
  }
 },
 {
  "id": "gate-cycle-time",
  "name": "Gate Cycle Time",
  "tagline": "2:40 average at the inbound gate. Peak hours hit 7 minutes. Now it's measured.",
  "category": "Manufacturing & Warehouse",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "slow_seconds",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 gate lane",
   "slow_seconds": "int (default 300)"
  }
 },
 {
  "id": "gate-tailgate-storage",
  "name": "Storage Gate Tailgate",
  "tagline": "One code, two cars. The gate camera saw it.",
  "category": "Security & Access",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "line",
   "window_seconds"
  ],
  "config_schema": {
   "line": "2-point gate crossing line",
   "window_seconds": "int \u2014 second-crossing window (default 8)"
  }
 },
 {
  "id": "supply-theft-watch",
  "name": "Supply Zone Theft Watch",
  "tagline": "Someone at the chemical shed at 11pm. Clip saved, phone pinged.",
  "category": "Security & Access",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "work_hours",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 supply storage",
   "work_hours": "[start,end] (default [6,19])"
  }
 },
 {
  "id": "greenhouse-visual-health",
  "name": "Canopy Visual Health",
  "tagline": "The canopy yellowed 8% this week. The camera caught it before the walkthrough.",
  "category": "Intelligence",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "check_hour",
   "hue_shift",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 canopy area",
   "hue_shift": "float \u2014 alert threshold (default 6.0)",
   "check_hour": "int \u2014 daily check (default 12)"
  }
 },
 {
  "id": "gym-equipment-usage",
  "name": "Equipment Usage Analytics",
  "tagline": "The leg press gets 4.2 hours a day. The ab machine gets 11 minutes.",
  "category": "People & Safety",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "digest_hour",
   "stations"
  ],
  "config_schema": {
   "stations": "map of machine-name \u2192 polygon",
   "digest_hour": "int (default 22)"
  }
 },
 {
  "id": "gym-occupancy-class",
  "name": "Class Attendance Counter",
  "tagline": "12 booked, 5 showed. Now your schedule knows.",
  "category": "People & Safety",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "class_windows",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 studio floor",
   "class_windows": "[[start,end],...] hours"
  }
 },
 {
  "id": "hall-pass-monitor",
  "name": "Hall Pass Monitor",
  "tagline": "Corridor roaming during class blocks, logged for the dean's office.",
  "category": "People & Safety",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "class_hours",
   "passing_minutes",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 hallway",
   "class_hours": "[start,end] (default [8,15])",
   "passing_minutes": "int \u2014 gap at hour start (default 10)"
  }
 },
 {
  "id": "hallway-overnight",
  "name": "Hallway Overnight Presence",
  "tagline": "Someone is in building C at 2am. Tenant, thief, or resident \u2014 you need to know which.",
  "category": "Security & Access",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "after_hours",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 interior hallway",
   "after_hours": "[start,end] (default [21,6])"
  }
 },
 {
  "id": "hand-hygiene",
  "name": "Hand Hygiene Compliance",
  "tagline": "Entered the kitchen without the sink stop. Logged.",
  "category": "Compliance",
  "tier": "enterprise",
  "requires_gpu": true,
  "config_keys": [
   "protected_zone",
   "sink_zone",
   "window_seconds"
  ],
  "config_schema": {
   "sink_zone": "polygon \u2014 handwash/sanitizer station",
   "protected_zone": "polygon \u2014 kitchen line / patient room",
   "window_seconds": "int \u2014 sink-within window (default 120)"
  }
 },
 {
  "id": "handicap-stall-monitor",
  "name": "Accessible Stall Usage Log",
  "tagline": "Every use of the accessible stalls, logged \u2014 plus the suspiciously fast ones.",
  "category": "Automotive & Parking",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "fast_minutes",
   "stalls"
  ],
  "config_schema": {
   "stalls": "map of stall-name \u2192 polygon",
   "fast_minutes": "int \u2014 flag turns under this (default 3)"
  }
 },
 {
  "id": "hangar-door-state",
  "name": "Hangar Door After-Hours",
  "tagline": "Hangar 3's door is open at 11pm. Nobody's scheduled.",
  "category": "Security & Access",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "after_hours",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 door face",
   "after_hours": "[start,end] (default [19,7])"
  }
 },
 {
  "id": "housekeeping-pace",
  "name": "Housekeeping Pace Tracker",
  "tagline": "22 minutes per room, 14 rooms per shift. Finally measured.",
  "category": "Intelligence",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "digest_hour",
   "room_doors"
  ],
  "config_schema": {
   "room_doors": "map of room-name \u2192 door polygon",
   "digest_hour": "int (default 16)"
  }
 },
 {
  "id": "ice-cooler-stock",
  "name": "Ice Cooler Stock Watch",
  "tagline": "Empty ice cooler on a 90-degree Saturday. Now it texts you.",
  "category": "Retail & QSR",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "check_minutes",
   "drop_ratio",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 cooler face",
   "drop_ratio": "float vs stocked baseline (default 0.4)",
   "check_minutes": "int \u2014 check cadence (default 30)"
  }
 },
 {
  "id": "impound-yard-log",
  "name": "Impound Yard In/Out Log",
  "tagline": "In at 2:14pm Tuesday, out at 9:03am Thursday. Billing stops arguing.",
  "category": "Automotive & Parking",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "line"
  ],
  "config_schema": {
   "line": "2-point yard crossing line"
  }
 },
 {
  "id": "kennel-restlessness",
  "name": "Kennel Restlessness Score",
  "tagline": "Run 12 paced all night. The morning report said so, with numbers.",
  "category": "Intelligence",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "digest_hour",
   "kennels"
  ],
  "config_schema": {
   "kennels": "map of kennel-name \u2192 polygon",
   "digest_hour": "int (default 7)"
  }
 },
 {
  "id": "lab-coat-zone",
  "name": "Clinical Zone Access Check",
  "tagline": "A vendor in the clinical corridor without scrubs. Flagged.",
  "category": "Healthcare & Senior Living",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "clinical_hue",
   "min_ratio",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 clinical corridor",
   "clinical_hue": "[low,high] HSV band for scrubs/whites (default [0,180] low-sat high-val = white)",
   "min_ratio": "float (default 0.2)"
  }
 },
 {
  "id": "laundromat-overnight",
  "name": "Laundromat Overnight Watch",
  "tagline": "Someone's been sitting on the folding table for two hours at 3am.",
  "category": "Security & Access",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "watch_hours",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 store floor",
   "watch_hours": "[start,end] (default [1,5])"
  }
 },
 {
  "id": "library-zone-count",
  "name": "Library Zone Counts",
  "tagline": "The kids' room peaks at 4pm on school days. The budget narrative just got data.",
  "category": "Intelligence",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "digest_hour",
   "zones"
  ],
  "config_schema": {
   "zones": "map of zone-name \u2192 polygon",
   "digest_hour": "int (default 20)"
  }
 },
 {
  "id": "lighting-outage",
  "name": "Lighting Outage Watch",
  "tagline": "The parking lot light that's been out for a week? Found in a day.",
  "category": "Property & Liability",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "lit_hours",
   "min_luma",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 lit area (optional: whole frame)",
   "min_luma": "float 0-255 (default 40)",
   "lit_hours": "[start,end] hours 0-23 (default [18,6] = overnight)"
  }
 },
 {
  "id": "livestock-down",
  "name": "Livestock Down Alert",
  "tagline": "The downer in pen 6, found at 2am instead of the morning round.",
  "category": "People & Safety",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "min_blob_ratio",
   "still_minutes",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 pen area",
   "still_minutes": "int (default 45)",
   "min_blob_ratio": "float \u2014 animal-sized blob (default 0.02)"
  }
 },
 {
  "id": "lobby-visitor-flow",
  "name": "Lobby Visitor Flow",
  "tagline": "Tuesday 11am is your real rush. Staff it like you know.",
  "category": "Intelligence",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "digest_hour",
   "line"
  ],
  "config_schema": {
   "line": "2-point entry counting line",
   "digest_hour": "int (default 17)"
  }
 },
 {
  "id": "loitering-watch",
  "name": "Loitering Watch",
  "tagline": "Still there after 10 minutes. Someone should take a look.",
  "category": "People & Safety",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "active_hours",
   "loiter_minutes",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 watch area",
   "loiter_minutes": "int (default 10)",
   "active_hours": "[start,end] optional"
  }
 },
 {
  "id": "lot-inventory-count",
  "name": "Lot Inventory Count",
  "tagline": "Row D is one car short vs the DMS. Found at 3am, not at month-end.",
  "category": "Automotive & Parking",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "count_hour",
   "rows"
  ],
  "config_schema": {
   "rows": "map of row-name \u2192 polygon",
   "count_hour": "int \u2014 quiet-hours count (default 3)"
  }
 },
 {
  "id": "lot-occupancy",
  "name": "Parking Lot Occupancy",
  "tagline": "Live lot count. Full-lot alerts. Zero sensors in the pavement.",
  "category": "Automotive & Parking",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "capacity",
   "full_ratio",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 lot area",
   "capacity": "int \u2014 total spaces",
   "full_ratio": "float \u2014 alert at this fill (default 0.95)"
  }
 },
 {
  "id": "machine-idle",
  "name": "Machine Idle Watch",
  "tagline": "Which machines actually ran this shift \u2014 from video, not sensors.",
  "category": "Manufacturing & Warehouse",
  "tier": "enterprise",
  "requires_gpu": true,
  "config_keys": [
   "machines",
   "motion_threshold"
  ],
  "config_schema": {
   "machines": "map of machine-name \u2192 polygon",
   "motion_threshold": "float \u2014 active energy level (default 0.02)"
  }
 },
 {
  "id": "machine-monopoly",
  "name": "Machine Monopoly Watch",
  "tagline": "One customer, eight machines, forty minutes. The Saturday regulars are glaring.",
  "category": "Retail & QSR",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "dwell_minutes",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 machine row approach",
   "dwell_minutes": "int (default 40)"
  }
 },
 {
  "id": "magnet-crane-exclusion",
  "name": "Magnet Crane Exclusion",
  "tagline": "Person under the magnet while it's live. The operator's cab buzzer fires.",
  "category": "People & Safety",
  "tier": "enterprise",
  "requires_gpu": true,
  "config_keys": [
   "hold_ms",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 exclusion area under crane/magnet path",
   "hold_ms": "int (default 400)"
  }
 },
 {
  "id": "mandated-camera-check",
  "name": "Mandated Camera Coverage Check",
  "tagline": "The vault camera got nudged Tuesday. The inspector comes Friday.",
  "category": "Compliance",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "check_hour",
   "edge_drop_ratio",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 mandated view region",
   "edge_drop_ratio": "float vs baseline (default 0.5)",
   "check_hour": "int (default 6)"
  }
 },
 {
  "id": "medspa-room-turn",
  "name": "Treatment Room Turn",
  "tagline": "Room 2 turns in 6 minutes. Room 4 takes 22. Now scheduling knows.",
  "category": "Intelligence",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "idle_alert_minutes",
   "rooms"
  ],
  "config_schema": {
   "rooms": "map of room-name \u2192 polygon",
   "idle_alert_minutes": "int (default 30)"
  }
 },
 {
  "id": "meeting-room-usage",
  "name": "Meeting Room Reality",
  "tagline": "Booked solid on the calendar. Empty since Tuesday. Measured.",
  "category": "Intelligence",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "digest_hour",
   "rooms"
  ],
  "config_schema": {
   "rooms": "map of room-name \u2192 polygon",
   "digest_hour": "int (default 18)"
  }
 },
 {
  "id": "mri-zone-safety",
  "name": "MRI Zone IV Safety",
  "tagline": "Someone is approaching the magnet room unescorted. Right now.",
  "category": "Healthcare & Senior Living",
  "tier": "enterprise",
  "requires_gpu": true,
  "config_keys": [
   "staffed_hours",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 Zone III/IV approach",
   "staffed_hours": "[start,end] \u2014 suppress during staffed hours (optional)"
  }
 },
 {
  "id": "nap-room-check",
  "name": "Nap Room Check",
  "tagline": "Nap time with movement, or pickup time with a child still there. Both caught.",
  "category": "People & Safety",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "nap_hours",
   "still_minutes",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 nap room",
   "nap_hours": "[start,end] (default [12,14])",
   "still_minutes": "int \u2014 all-still check after hours (default 30)"
  }
 },
 {
  "id": "overnight-parking",
  "name": "Overnight Parking Watch",
  "tagline": "Posted no overnight parking. There's a van. It's 2am. Documented.",
  "category": "Automotive & Parking",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "closed_hours",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 lot area",
   "closed_hours": "[start,end] (default [22,6])"
  }
 },
 {
  "id": "pace-of-play",
  "name": "Pace of Play Monitor",
  "tagline": "22-minute gap after the group on 7. The marshal knows which cart.",
  "category": "Intelligence",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "slow_gap_minutes",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 tee box approach",
   "slow_gap_minutes": "int (default 15)"
  }
 },
 {
  "id": "pallet-count",
  "name": "Pallet Count",
  "tagline": "The floor count vs the system count \u2014 settled by camera.",
  "category": "Manufacturing & Warehouse",
  "tier": "enterprise",
  "requires_gpu": true,
  "config_keys": [
   "max_area_ratio",
   "min_area_ratio",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 staging area",
   "min_area_ratio": "float \u2014 min object size vs frame (default 0.005)",
   "max_area_ratio": "float \u2014 max object size (default 0.15)"
  }
 },
 {
  "id": "pavilion-rental",
  "name": "Pavilion Rental Verification",
  "tagline": "Pavilion 2 is packed and nobody rented it. Or it's rented and empty. Either way, logged.",
  "category": "Compliance",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "min_persons",
   "rental_windows",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 pavilion",
   "rental_windows": "[[start,end],...] hours rented (default [])",
   "min_persons": "int \u2014 occupied threshold (default 4)"
  }
 },
 {
  "id": "pay-station-queue",
  "name": "Pay Station Queue",
  "tagline": "Four people deep at the pay machine at 5:55pm. One of them is about to bail on the ticket.",
  "category": "Automotive & Parking",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "hold_seconds",
   "max_queue",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 pay station approach",
   "max_queue": "int (default 3)",
   "hold_seconds": "int (default 45)"
  }
 },
 {
  "id": "pest-watch",
  "name": "Pest Watch (After-Hours)",
  "tagline": "Small, fast, floor-level, 2am. You want to know.",
  "category": "Compliance",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "active_hours",
   "min_speed",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 kitchen/storage floor",
   "active_hours": "[start,end] \u2014 closed hours (default [22,5])",
   "min_speed": "float \u2014 blob speed proxy (default 0.02 norm/frame)"
  }
 },
 {
  "id": "pharmacy-window-queue",
  "name": "Pharmacy Window Queue",
  "tagline": "Pickup line length and per-person wait, measured continuously.",
  "category": "Healthcare & Senior Living",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "max_line",
   "wait_alert_minutes",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 pickup line area",
   "max_line": "int (default 5)",
   "wait_alert_minutes": "int (default 15)"
  }
 },
 {
  "id": "play-yard-cluster",
  "name": "Play Yard Scuffle Alert",
  "tagline": "Sudden chaos in the yard. Staff alerted in seconds, clip attached.",
  "category": "People & Safety",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "energy_spike",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 play yard",
   "energy_spike": "float \u2014 vs rolling baseline (default 3.0)"
  }
 },
 {
  "id": "playground-alone",
  "name": "Playground Alone Alert",
  "tagline": "One small figure on the playground at 3:45pm. Someone should walk out there.",
  "category": "People & Safety",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "max_height_ratio",
   "recess_windows",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 playground/field",
   "recess_windows": "[[start,end],...] hours (default [[9,11],[13,14]])",
   "max_height_ratio": "float \u2014 child proxy (default 0.35)"
  }
 },
 {
  "id": "pool-capacity",
  "name": "Pool Bather Load",
  "tagline": "Over posted capacity at the pool, documented and alerted.",
  "category": "People & Safety",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "hold_seconds",
   "max_bathers",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 pool + deck",
   "max_bathers": "int (default 20)",
   "hold_seconds": "int (default 45)"
  }
 },
 {
  "id": "pool-drowning-watch",
  "name": "Pool Distress Watch",
  "tagline": "Motionless in the water for 20 seconds. This is the call that matters.",
  "category": "People & Safety",
  "tier": "enterprise",
  "requires_gpu": true,
  "config_keys": [
   "still_seconds",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 water only (not deck)",
   "still_seconds": "int (default 20)"
  }
 },
 {
  "id": "pump-dwell",
  "name": "Pump Dwell Time",
  "tagline": "A car camping at pump 4 during rush costs you three sales an hour.",
  "category": "Automotive & Parking",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "slow_minutes",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 pump island",
   "slow_minutes": "int (default 12)"
  }
 },
 {
  "id": "pump-turns",
  "name": "Pump Turn Counter",
  "tagline": "Pump 2 turned 41 cars today. Pump 5 turned 9. Now you know why the line forms.",
  "category": "Intelligence",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "digest_hour",
   "pumps"
  ],
  "config_schema": {
   "pumps": "map of pump-name \u2192 polygon",
   "digest_hour": "int (default 22)"
  }
 },
 {
  "id": "queue-length",
  "name": "Queue Length Monitor",
  "tagline": "Know the moment a line forms \u2014 before customers walk out.",
  "category": "Retail & QSR",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "hold_seconds",
   "max_length",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 queue area (normalized)",
   "max_length": "int \u2014 persons before alert (default 4)",
   "hold_seconds": "int \u2014 sustained duration (default 30)"
  }
 },
 {
  "id": "rack-door-open",
  "name": "Rack Door Watch",
  "tagline": "Cabinet 14's door has been open for 20 minutes. The badge log says nobody.",
  "category": "Security & Access",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "open_minutes",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 cabinet/row door",
   "open_minutes": "int (default 15)"
  }
 },
 {
  "id": "range-utilization",
  "name": "Driving Range Utilization",
  "tagline": "Bay 1-8 full until 10, dead by 2. The pricing sheet should know.",
  "category": "Intelligence",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "bays",
   "digest_hour"
  ],
  "config_schema": {
   "bays": "map of bay-name \u2192 polygon",
   "digest_hour": "int (default 21)"
  }
 },
 {
  "id": "repeat-visitor",
  "name": "Repeat Visitor Pattern",
  "tagline": "Same jacket, three nights in a row, walking the fence line. Flagged.",
  "category": "Intelligence",
  "tier": "enterprise",
  "requires_gpu": true,
  "config_keys": [
   "visits_threshold",
   "window_days"
  ],
  "config_schema": {
   "visits_threshold": "int \u2014 distinct sessions before flag (default 3)",
   "window_days": "int (default 7)"
  }
 },
 {
  "id": "route-verification",
  "name": "Service Route Verification",
  "tagline": "The sweeper hit zone 12 at 4:40am. Proven, timestamped, done.",
  "category": "Intelligence",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "window",
   "zones"
  ],
  "config_schema": {
   "zones": "map of route-zone \u2192 polygon",
   "window": "[start,end] hours the route should cover zones"
  }
 },
 {
  "id": "safety-zone-breach",
  "name": "Safety Zone Breach",
  "tagline": "Person in the press cell. Alert in under a second.",
  "category": "Manufacturing & Warehouse",
  "tier": "enterprise",
  "requires_gpu": true,
  "config_keys": [
   "hold_ms",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 restricted area",
   "hold_ms": "int \u2014 debounce (default 300)"
  }
 },
 {
  "id": "sanctuary-count",
  "name": "Service Attendance Count",
  "tagline": "9am: 212. 11am: 347. The attendance report writes itself.",
  "category": "Intelligence",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "service_windows",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 sanctuary",
   "service_windows": "[[start,end],...] hours (default [[9,10],[11,12]])"
  }
 },
 {
  "id": "scrap-scale-queue",
  "name": "Scale House Queue",
  "tagline": "Six trucks at the scale and one working it. Dispatch knows before the drivers call.",
  "category": "Manufacturing & Warehouse",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "max_queue",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 scale approach lane",
   "max_queue": "int (default 4)"
  }
 },
 {
  "id": "seal-check",
  "name": "Trailer Seal Check",
  "tagline": "Trailer doors open in the parking row, not the dock. That's pilferage.",
  "category": "Manufacturing & Warehouse",
  "tier": "enterprise",
  "requires_gpu": true,
  "config_keys": [
   "diff_ratio",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 trailer rear area in parking row",
   "diff_ratio": "float (default 0.15)"
  }
 },
 {
  "id": "service-lane-cycle",
  "name": "Service Lane Cycle Time",
  "tagline": "Average write-up-to-exit: 3h 12m today. The OEM scorecard knows \u2014 now you do too.",
  "category": "Automotive & Parking",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "entry_zone",
   "exit_zone",
   "slow_hours"
  ],
  "config_schema": {
   "entry_zone": "polygon \u2014 write-up lane",
   "exit_zone": "polygon \u2014 service exit",
   "slow_hours": "float (default 5)"
  }
 },
 {
  "id": "service-response-time",
  "name": "Service Response Time",
  "tagline": "Customer needed help at 2:04:12. Staff arrived 2:07:48. Measured, every time.",
  "category": "Intelligence",
  "tier": "enterprise",
  "requires_gpu": true,
  "config_keys": [
   "staff_zone",
   "target_seconds",
   "trigger_zone"
  ],
  "config_schema": {
   "trigger_zone": "polygon \u2014 customer trigger point",
   "staff_zone": "polygon \u2014 where staff arrive",
   "target_seconds": "int \u2014 SLA target (default 180)"
  }
 },
 {
  "id": "shelf-stockout",
  "name": "Shelf Stockout Alert",
  "tagline": "Empty shelf at 2pm = lost sales all afternoon.",
  "category": "Retail & QSR",
  "tier": "enterprise",
  "requires_gpu": true,
  "config_keys": [
   "drop_ratio",
   "learn_frames",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 shelf area",
   "drop_ratio": "float \u2014 density drop vs baseline (default 0.35)",
   "learn_frames": "int \u2014 baseline frames to average (default 50)"
  }
 },
 {
  "id": "shelter-census",
  "name": "Shelter Overnight Census",
  "tagline": "Tuesday census: 47. Reported to the funder automatically.",
  "category": "Intelligence",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "census_hour",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 bunk area",
   "census_hour": "int (default 2)"
  }
 },
 {
  "id": "site-theft-watch",
  "name": "Construction Site Theft Watch",
  "tagline": "Copper walks off at midnight. Now it walks off on camera, flagged.",
  "category": "Security & Access",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "crew_hours",
   "weekends_active",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 laydown yard / equipment",
   "crew_hours": "[start,end] (default [6,17])",
   "weekends_active": "bool (default true)"
  }
 },
 {
  "id": "slip-fall",
  "name": "Slip & Fall Liability Guard",
  "tagline": "Someone fell. The clip is already saved.",
  "category": "Property & Liability",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "confidence",
   "floor_angle_seconds"
  ],
  "config_schema": {
   "confidence": "float (default 0.55)",
   "floor_angle_seconds": "float (default 1.5)"
  }
 },
 {
  "id": "snow-ice-watch",
  "name": "Snow & Ice Watch",
  "tagline": "White walk at 6am, crew dispatched by 6:05. Documentation included.",
  "category": "Property & Liability",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "white_ratio",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 walk/entrance",
   "white_ratio": "float (default 0.45)"
  }
 },
 {
  "id": "specimen-chain",
  "name": "Specimen Drop Verification",
  "tagline": "Every drop logged with a timestamp. Every missing one flagged.",
  "category": "Healthcare & Senior Living",
  "tier": "enterprise",
  "requires_gpu": true,
  "config_keys": [
   "min_dwell_seconds",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 specimen drop area",
   "min_dwell_seconds": "int \u2014 deposit confirmation dwell (default 10)"
  }
 },
 {
  "id": "splash-pad-capacity",
  "name": "Splash Pad Capacity",
  "tagline": "Posted limit 40. Count is 52. The alert went to the field supervisor.",
  "category": "People & Safety",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "hold_seconds",
   "max_persons",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 splash pad",
   "max_persons": "int (default 40)",
   "hold_seconds": "int (default 60)"
  }
 },
 {
  "id": "table-turn",
  "name": "Table Turn Tracker",
  "tagline": "Which tables turn fast, which sit empty, and for how long.",
  "category": "Retail & QSR",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "empty_alert_minutes",
   "tables"
  ],
  "config_schema": {
   "tables": "map of table-name \u2192 polygon",
   "empty_alert_minutes": "int \u2014 table empty this long during open hours (default 45)"
  }
 },
 {
  "id": "tarmac-fod",
  "name": "Tarmac FOD Watch",
  "tagline": "Something's on the ramp that wasn't there this morning. Found before the prop did.",
  "category": "People & Safety",
  "tier": "enterprise",
  "requires_gpu": true,
  "config_keys": [
   "new_object_seconds",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 ramp area",
   "new_object_seconds": "int \u2014 persistence to alert (default 120)"
  }
 },
 {
  "id": "teller-line-pace",
  "name": "Teller Line Pace",
  "tagline": "Average branch wait: 4:12 today. The board report writes itself.",
  "category": "Intelligence",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "digest_hour",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 teller line",
   "digest_hour": "int (default 16)"
  }
 },
 {
  "id": "tenant-after-hours",
  "name": "Per-Tenant After-Hours Watch",
  "tagline": "Suite 410's zone, suite 410's hours, suite 410's alerts.",
  "category": "Security & Access",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "suites"
  ],
  "config_schema": {
   "suites": "map of suite-name \u2192 {polygon, hours: [start,end]}"
  }
 },
 {
  "id": "thermal-shimmer",
  "name": "Thermal Shimmer Watch",
  "tagline": "The exhaust plume changed shape at 2pm. The temp sensor noticed at 2:40.",
  "category": "Intelligence",
  "tier": "enterprise",
  "requires_gpu": true,
  "config_keys": [
   "variance_shift",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 exhaust area",
   "variance_shift": "float \u2014 vs baseline (default 0.5)"
  }
 },
 {
  "id": "truck-turn-time",
  "name": "Truck Turn Time",
  "tagline": "How long each truck actually sat at your dock \u2014 per carrier.",
  "category": "Manufacturing & Warehouse",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "slow_minutes",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 yard/dock area",
   "slow_minutes": "int \u2014 alert threshold (default 120)"
  }
 },
 {
  "id": "two-person-rule",
  "name": "Two-Person Rule",
  "tagline": "One person in the server room for 4 minutes. SOC 2 auditor never sees it \u2014 you already fixed it.",
  "category": "Compliance",
  "tier": "enterprise",
  "requires_gpu": true,
  "config_keys": [
   "solo_seconds",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 server room",
   "solo_seconds": "int (default 240)"
  }
 },
 {
  "id": "uniform-check",
  "name": "Uniform Compliance Check",
  "tagline": "Who's on the floor without the uniform? The camera knows.",
  "category": "Compliance",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "min_ratio",
   "uniform_hue",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 staff-only area",
   "uniform_hue": "[low, high] HSV hue band (default [90, 130] = blue scrubs)",
   "min_ratio": "float \u2014 min uniform pixels (default 0.25)"
  }
 },
 {
  "id": "unit-door-open",
  "name": "Storage Unit Door Watch",
  "tagline": "Unit 214's door has been up for 40 minutes. Someone should walk the row.",
  "category": "Security & Access",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "open_minutes",
   "units"
  ],
  "config_schema": {
   "units": "map of unit-name \u2192 door polygon",
   "open_minutes": "int (default 30)"
  }
 },
 {
  "id": "unit-fullness",
  "name": "Unit Fullness Audit",
  "tagline": "Unit 87 is 90% full, not empty. The auction listing just changed.",
  "category": "Intelligence",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "empty_ratio",
   "units"
  ],
  "config_schema": {
   "units": "map of unit-name \u2192 interior polygon",
   "empty_ratio": "float \u2014 edge density below = empty (default 0.02)"
  }
 },
 {
  "id": "vault-approach",
  "name": "Vault Two-Person Rule",
  "tagline": "One person at the vault, alone, for 90 seconds. Compliance has the clip.",
  "category": "Compliance",
  "tier": "enterprise",
  "requires_gpu": true,
  "config_keys": [
   "solo_seconds",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 vault approach",
   "solo_seconds": "int (default 90)"
  }
 },
 {
  "id": "vehicle-damage-scan",
  "name": "Vehicle Damage Scan",
  "tagline": "New scratch on a lot vehicle? Dated before/after frames settle it.",
  "category": "Automotive & Parking",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "diff_ratio",
   "scan_hour",
   "stalls"
  ],
  "config_schema": {
   "stalls": "map of stall-name \u2192 polygon",
   "diff_ratio": "float \u2014 change threshold (default 0.12)",
   "scan_hour": "int \u2014 daily scan hour (default 7)"
  }
 },
 {
  "id": "vending-route-verify",
  "name": "Vending Route Verification",
  "tagline": "Bank 4 got a 40-second drive-by, not a service visit. The log says so.",
  "category": "Intelligence",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "banks",
   "min_service_seconds"
  ],
  "config_schema": {
   "banks": "map of bank-name \u2192 polygon",
   "min_service_seconds": "int \u2014 real visit threshold (default 180)"
  }
 },
 {
  "id": "vendor-verification",
  "name": "Vendor Arrival Verification",
  "tagline": "Scheduled 9-11am. Arrived 6:40am. Flagged.",
  "category": "Intelligence",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "weekdays_only",
   "window_end",
   "window_start",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 vendor entrance",
   "window_start": "int hour (default 8)",
   "window_end": "int hour (default 17)",
   "weekdays_only": "bool (default true)"
  }
 },
 {
  "id": "viewing-room-privacy",
  "name": "Viewing Room Privacy Window",
  "tagline": "Someone entered viewing room B during setup. Staff knew before the door opened.",
  "category": "Compliance",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "scheduled_windows",
   "suppress_staff_hours",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 viewing room entry",
   "scheduled_windows": "[[start,end],...] hours open to visitors (default [])",
   "suppress_staff_hours": "[start,end] optional staff-only hours that never alert"
  }
 },
 {
  "id": "visitor-badge-check",
  "name": "Visitor Badge Check",
  "tagline": "No badge patch on the sales floor. Flagged in real time.",
  "category": "Compliance",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "badge_hue",
   "min_ratio",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 controlled floor",
   "badge_hue": "[low,high] HSV badge color band (default [0,10] = red)",
   "min_ratio": "float (default 0.02)"
  }
 },
 {
  "id": "waiting-room-overflow",
  "name": "Waiting Room Overflow",
  "tagline": "The lobby hit 14 people at 9:12am. Triage got pinged at 9:12am.",
  "category": "Healthcare & Senior Living",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "hold_seconds",
   "max_persons",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 waiting area",
   "max_persons": "int (default 12)",
   "hold_seconds": "int (default 60)"
  }
 },
 {
  "id": "wash-bay-pace",
  "name": "Wash Bay Pace",
  "tagline": "Bay 3 is running 40% slower than the others. The camera noticed first.",
  "category": "Automotive & Parking",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "bays",
   "slow_seconds"
  ],
  "config_schema": {
   "bays": "map of bay-name \u2192 polygon",
   "slow_seconds": "int (default 420)"
  }
 },
 {
  "id": "wash-bay-queue",
  "name": "Service Bay Queue",
  "tagline": "Five trucks deep at the wash bay at shift change. Dispatch already knows.",
  "category": "Manufacturing & Warehouse",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "max_queue",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 queue lane",
   "max_queue": "int (default 3)"
  }
 },
 {
  "id": "wrong-way",
  "name": "Wrong-Way Movement",
  "tagline": "One-way means one-way \u2014 even at 2am when nobody's watching.",
  "category": "People & Safety",
  "tier": "starter",
  "requires_gpu": true,
  "config_keys": [
   "forbidden",
   "line"
  ],
  "config_schema": {
   "line": "2-point crossing line",
   "forbidden": "'forward' or 'backward' \u2014 which crossing direction alerts"
  }
 },
 {
  "id": "yard-dwell",
  "name": "Trailer Yard Dwell",
  "tagline": "That trailer's been in row C for 6 days. The camera noticed on day one.",
  "category": "Manufacturing & Warehouse",
  "tier": "pro",
  "requires_gpu": true,
  "config_keys": [
   "stale_hours",
   "zone"
  ],
  "config_schema": {
   "zone": "polygon \u2014 yard area",
   "stale_hours": "int \u2014 stale trailer alert (default 72)"
  }
 }
];
