#!/usr/bin/env python3
"""Regenerate the storefront ItemList JSON-LD from the marketplace catalog.

The storefront renders its 100 functions client-side, so none of the catalog
reaches crawlers or AI answer engines as structured data. This emits a
CollectionPage + ItemList graph describing every catalog entry and splices it
into the marked region of storefront/index.html.

Run after any catalog change:

    python3 scripts/generate_seo_schema.py

Exits non-zero if the markers are missing or the catalog cannot be read, so a
drifted page fails closed rather than shipping stale structured data.
"""

from __future__ import annotations

import json
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "storefront" / "catalog.json"
PAGE = ROOT / "storefront" / "index.html"

START = "<!-- SEO-SCHEMA:START (generated by scripts/generate_seo_schema.py) -->"
END = "<!-- SEO-SCHEMA:END -->"

ORG = {
    "@type": "Organization",
    "name": "Nexus Communications Technology",
    "url": "https://nexusct.com",
}


def load_catalog() -> list[dict]:
    if not CATALOG.exists():
        sys.exit(f"catalog not found: {CATALOG}")
    data = json.loads(CATALOG.read_text(encoding="utf-8"))
    entries = data if isinstance(data, list) else data.get("functions", [])
    if not entries:
        sys.exit("catalog is empty; refusing to emit an empty ItemList")
    return entries


def build_item(entry: dict, position: int) -> dict:
    """One catalog entry as a SoftwareApplication list item.

    Plan tier and GPU requirement are carried as additionalProperty rather than
    offers: pricing is per-plan, not per-function, so a per-item price would be
    a fabricated claim.
    """
    props = [
        {
            "@type": "PropertyValue",
            "name": "Plan tier",
            "value": str(entry.get("tier", "")).title(),
        },
        {
            "@type": "PropertyValue",
            "name": "Requires GPU",
            "value": "Yes" if entry.get("requires_gpu") else "No",
        },
    ]
    # provider / operatingSystem / applicationCategory are identical for every
    # entry, so they are declared once on the ItemList rather than 100 times.
    return {
        "@type": "ListItem",
        "position": position,
        "item": {
            "@type": "SoftwareApplication",
            "@id": f"#function-{entry['id']}",
            "name": entry["name"],
            "description": entry.get("tagline", ""),
            "applicationSubCategory": entry.get("category", ""),
            "isPartOf": {"@id": "#nexus-vision"},
            "additionalProperty": props,
        },
    }


def build_graph(entries: list[dict]) -> dict:
    categories = sorted({e.get("category", "") for e in entries if e.get("category")})
    today = date.today().isoformat()
    return {
        "@context": "https://schema.org",
        "@graph": [
            {
                "@type": "CollectionPage",
                "name": "Nexus Vision Marketplace",
                "description": (
                    f"Catalog of {len(entries)} GPU-accelerated video analytics "
                    f"functions for UniFi Protect NVRs, across {len(categories)} "
                    "operational categories."
                ),
                "dateModified": today,
                "provider": ORG,
                "about": [{"@type": "Thing", "name": c} for c in categories],
                "mainEntity": {"@id": "#marketplace-catalog"},
            },
            {
                "@type": "SoftwareApplication",
                "@id": "#nexus-vision",
                "name": "Nexus Vision",
                "applicationCategory": "SecurityApplication",
                "operatingSystem": "Docker (Linux, NVIDIA GPU)",
                "description": (
                    "GPU-accelerated AI function marketplace for UniFi Protect "
                    f"NVRs, with {len(entries)} on-premises video analytics functions."
                ),
                "provider": ORG,
            },
            {
                "@type": "ItemList",
                "@id": "#marketplace-catalog",
                "name": "Nexus Vision marketplace functions",
                "numberOfItems": len(entries),
                "itemListOrder": "https://schema.org/ItemListOrderAscending",
                "itemListElement": [
                    build_item(e, i)
                    for i, e in enumerate(
                        sorted(entries, key=lambda x: x["name"]), start=1
                    )
                ],
            },
        ],
    }


def main() -> None:
    entries = load_catalog()
    graph = build_graph(entries)
    block = (
        f"{START}\n"
        '<script type="application/ld+json">\n'
        f"{json.dumps(graph, indent=2, ensure_ascii=False)}\n"
        "</script>\n"
        f"{END}"
    )

    html = PAGE.read_text(encoding="utf-8")
    if START not in html or END not in html:
        sys.exit(f"markers not found in {PAGE}; expected {START} ... {END}")
    head, _, rest = html.partition(START)
    _, _, tail = rest.partition(END)
    PAGE.write_text(head + block + tail, encoding="utf-8")

    print(f"wrote {len(entries)} ItemList entries to {PAGE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
